<a href="https://colab.research.google.com/github/Ayman-Abdeen/data_analysis_NumPy/blob/main/numpy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [5]:
# Dimensions
# 0-D array
a = np.array(120)
print('0 d array:\n', a)

print('\n---------- Dimensions ----------')

# 1-D array
one_d = np.array([3, 1, 7, 5])
print('1 d array:\n', one_d)

print('\n---------- Dimensions ----------')

# 2-D array
two_d = np.array([[1, 3, 2], [5, 6, 4]])
print('2 d array:\n', two_d)

print('\n---------- Dimensions ----------')

# 3-D array
three_d = np.array([[[1, 2], [2, 3]], [[3, 5], [6, 7]]])
print('3 d array:\n', three_d)

0 d array:
 120

---------- Dimensions ----------
1 d array:
 [3 1 7 5]

---------- Dimensions ----------
2 d array:
 [[1 3 2]
 [5 6 4]]

---------- Dimensions ----------
3 d array:
 [[[1 2]
  [2 3]]

 [[3 5]
  [6 7]]]


In [6]:
# Array attributes
print('Array dimensions:', two_d.ndim)
print('Array shape:', two_d.shape)

Array dimensions: 2
Array shape: (2, 3)


In [7]:
#Accessing/Indexing
print('first item in one d array:', one_d[0])
print('first item in two d array:', two_d[0, 0])
print('first item in three d array:', three_d[0, 0, 0])


first item in one d array: 3
first item in two d array: 1
first item in three d array: 1


In [8]:
# 1-d array iterating
for x in one_d:
    print(x)


3
1
7
5


In [9]:
# 2-d array iterating
print('Iterating over 2 d array')
for x in two_d:
    for y in x:
        print(y)

Iterating over 2 d array
1
3
2
5
6
4


In [10]:
# 3-d array iterating
print('Iterating over 3 d array')
for x in three_d:
    for y in x:
        for f in y:
            print(f)

Iterating over 3 d array
1
2
2
3
3
5
6
7


In [11]:
print('Iterating over all items in array using nditer:')
for x in np.nditer(two_d):
    print(x)


Iterating over all items in array using nditer:
1
3
2
5
6
4


In [12]:
#Search
# where function
print(np.where(two_d == 4))  # will find all indices match the condition
print(np.where(two_d % 2 == 0))  # will find all indices match the condition (all even numbers)

(array([1]), array([2]))
(array([0, 1, 1]), array([2, 1, 2]))


In [13]:
#Sort
print('Sorting array:\n', np.sort(one_d))
print('Sorting each row in array: \n', np.sort(two_d))


Sorting array:
 [1 3 5 7]
Sorting each row in array: 
 [[1 2 3]
 [4 5 6]]


In [14]:
#Random numbers
print('Random integer:', np.random.randint(100))
print('Random integer between 2 numbers:', np.random.randint(10, 80))
print('Random float ben 0-1:', np.random.rand())


Random integer: 56
Random integer between 2 numbers: 68
Random float ben 0-1: 0.744159251300566


In [15]:
#Array generation
print('Generating integer matrix 2x3 with random integer numbers:\n', np.random.randint(10, 90, size=(2, 3)))
print('Generating float matrix 2x3 with random numbers 0-1:\n', np.random.rand(2, 3))
print('Generating zeros matrix 2x3:\n', np.zeros((2, 3), int))
print('Generating ones matrix 2x3:\n', np.ones((2, 3), int))

Generating integer matrix 2x3 with random integer numbers:
 [[77 61 89]
 [38 73 52]]
Generating float matrix 2x3 with random numbers 0-1:
 [[0.45126248 0.58033366 0.19478375]
 [0.6688321  0.8290588  0.88130768]]
Generating zeros matrix 2x3:
 [[0 0 0]
 [0 0 0]]
Generating ones matrix 2x3:
 [[1 1 1]
 [1 1 1]]


In [16]:
#Transpose
two_d_t = two_d.T
print('original 2 d:\n', two_d, two_d.shape)
print('Transposed 2 d:\n', two_d_t, two_d_t.shape)

original 2 d:
 [[1 3 2]
 [5 6 4]] (2, 3)
Transposed 2 d:
 [[1 5]
 [3 6]
 [2 4]] (3, 2)


In [17]:
#copy
two_d_c = two_d.copy()
two_d_c[0, 1] = 1000192
print('Original 2d:\n', two_d)
print('copied 2d:\n', two_d_c)

Original 2d:
 [[1 3 2]
 [5 6 4]]
copied 2d:
 [[      1 1000192       2]
 [      5       6       4]]


In [18]:
#Mathematical operations
a = np.array([1, 2])
b = np.array([3, 4])
print('Result of a + b: ', np.add(a, b))
print('Result of a - b: ', np.subtract(a, b))
print('Result of a * b: ', np.multiply(a, b))
print('Result of a / b: ', np.divide(a, b))
print('Result of a ^ b: ', np.power(a, b))
print('Result of a ^ 2: ', np.power(a, 2))


Result of a + b:  [4 6]
Result of a - b:  [-2 -2]
Result of a * b:  [3 8]
Result of a / b:  [0.33333333 0.5       ]
Result of a ^ b:  [ 1 16]
Result of a ^ 2:  [1 4]


In [19]:
#Trigonometric operations
a = np.array([0, 1])
print(np.sin(a))
print(np.cos(a))

[0.         0.84147098]
[1.         0.54030231]


In [20]:
#Statistical functions 
a = two_d
print('Min item in array:', np.amin(a))
print('Max item in array:', np.amax(a))
print('Median of array:', np.median(a))
print('standard deviation of array:', np.std(a))
print('Average of array:', np.average(a))
print('Mean of array:', np.mean(a))
print('Variance of array:', np.var(a))

Min item in array: 1
Max item in array: 6
Median of array: 3.5
standard deviation of array: 1.707825127659933
Average of array: 3.5
Mean of array: 3.5
Variance of array: 2.9166666666666665


In [21]:
#Algebra functions
a = np.array([2, 4])
b = np.array([3, 5])
print('1-d Matrices multiplication:\n', np.matmul(a, b))

1-d Matrices multiplication:
 26


In [22]:
a = np.array([[2, 4], [1, 3]])
b = np.array([[3, 5], [4, 6]])
print('2-d Matrices multiplication:\n', np.matmul(a, b))

2-d Matrices multiplication:
 [[22 34]
 [15 23]]


In [24]:
#Algebra functions
a = np.array([1, 2, 3, 5, 6, 1, 2, 3, 4, 1, 1, 2, 6])
print('Histogram of array', np.histogram(a))

Histogram of array (array([4, 0, 3, 0, 2, 0, 1, 0, 1, 2]), array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ]))
